spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shoppizza
    username: user
    password: hackme
    initialization-mode: always
    schema: classpath*:database/init.sql
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
